# Site settings
title: Run You Clever Boy
email: 
description: And remember.
url: https://rycbar.me
title_description: And remember.
title_image: https://1drv.ms/u/s!AhGuVS9rBvJyq0zbBKHHTfw2kWHw?e=CUZKYY
google_analytics: UA-165015031-1
disqus_account: ellecheung@outlook.com
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: ellegenious
github_username: 
instagram_username: 

# Footer
footer_left: "─=≡Σ(((つ•̀ω•́)つ"
footer_right: "Hello? Goodbye."

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
