---
title: Run You Clever Boy
email: 
description: And remember.
url: https://rycbar.me
title_description: And remember.
title_image: ''
google_analytics: UA-165015031-1
disqus_account: ellecheung@outlook.com
addthis_id: 
post_limit: "5"
twitter_username: ellegenious
github_username: 
instagram_username: 
disqus_js: https://rycbar.disqus.com/embed.js
footer_left: "─=≡Σ(((つ•̀ω•́)つ"
footer_right: Hello? Goodbye.
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: "/:year/:month/:title/"
exclude:
- vendor
plugins:
- jekyll-sitemap
