# Site settings
title: Run You Clever Boy
email: 
description: And remember.
url: https://rycbar.me
title_description: And remember.
title_image: 
google_analytics: 
disqus_account: 
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username: 
instagram_username: 

# Footer
footer_left: "Made by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
